library(devtools)


install_github("AliciaSchep/gglabeller")
install_github("AntoineGuillot2/D3partitionR")
install_github("AppliedDataSciencePartners/xgboostExplainer")
install_github("bhaskarvk/leaflet.extras")
install_github("ColinFay/aside")
install_github("ColinFay/tidystringdist")
install_github("datacamp/RDocumentation")
install_github("dgrtwo/gganimate")
install_github("drsimonj/twidlr")
install_github("dyerlab/popgraph")
install_github("edgararuiz/dbplot")
install_github("EmilHvitfeldt/ggpage")
install_github("gabrielrvsc/HDeconometrics")
install_github("hadley/pkgdown")
install_github("hadley/precis")
install_github("hadley/strict")
install_github("hafen/trelliscopejs")
install_github("hrbrmstr/msgxtractr")
install_github("hrbrmstr/waffle")
install_github("jeremystan/aargh")
install_github("krlmlr/styler")
install_github("lantanacamara/lightgbmExplainer")
install_github("MilesMcBain/deplearning")
install_github("MilesMcBain/packup")
install_github("pbiecek/breakDown")
install_github("ropensci/tabulizer")
install_github("ropensci/tabulizerjars")
install_github("ropenscilabs/data-packages")
install_github("ropenscilabs/icon")
install_github("ropenscilabs/packagemetrics")
install_github("ropenscilabs/skimr")
install_github("rstats-db/RPostgres")
install_github("smach/rmiscutils")
install_github("ThinkR-open/remedy")
install_github("ThinkRstat/littleboxes")
install_github("trestletech/shinyAce")
install_github("vqv/ggbiplot")
install_github("wilkox/ggfittext")
install_github("swarm-lab/editR") # requires devtools::shinyAce shiny shinyFiles shinyBS rmarkdown knitr
# install_github("gsimchoni/kandinsky")
# install_github("MangoTheCat/goodpractice")
# install_github("MilesMcBain/gistfo")
# install_github("r-lib/boxes")
# install_github("rich-iannone/blastula")
# install_github("ropenscilabs/available")
# install_github("Stan125/GREA")
