library(devtools)

install_github("ColinFay/aside")
install_github("hrbrmstr/msgxtractr")
install_github("rstats-db/RPostgres")
install_github("vqv/ggbiplot")
install_github("rich-iannone/blastula")
install_github("ropensci/tabulizerjars")
install_github("ropensci/tabulizer")
install_github("ThinkRstat/littleboxes")
install_github("MangoTheCat/goodpractice")
install_github("hadley/pkgdown")
install_github("gsimchoni/kandinsky")
install_github("datacamp/RDocumentation")
install_github("edgararuiz/dbplot")
install_github("krlmlr/styler")
install_github("ThinkR-open/remedy")
install_github("AntoineGuillot2/D3partitionR")
install_github("hafen/trelliscopejs")
install_github("wilkox/ggfittext")
install_github("hrbrmstr/waffle")
install_github("bhaskarvk/leaflet.extras")
install_github("dgrtwo/gganimate")
install_github("EmilHvitfeldt/ggpage")
install_github("dyerlab/popgraph")
install_github("trestletech/shinyAce")
install_github("swarm-lab/editR") # requires devtools::shinyAce shiny shinyFiles shinyBS rmarkdown knitr
