library(devtools)

install_github("AliciaSchep/gglabeller")
install_github("AppliedDataSciencePartners/xgboostExplainer")
install_github("aryoda/tryCatchLog")
install_github("benmarwick/wordcountaddin", type = "source", dependencies = TRUE)
install_github("bhaskarvk/leaflet.extras")
install_github("christophM/iml")
install_github("cole-brokamp/rize")
install_github("ColinFay/aside")
install_github("colinfay/dockerfiler")
install_github("ColinFay/tidystringdist")
install_github("cttobin/ggthemr")
install_github("daranzolin/ViewPipeSteps")
install_github("datacamp/RDocumentation")
install_github("dgrtwo/gganimate")
install_github("drsimonj/twidlr")
install_github("dyerlab/popgraph")
install_github("edgararuiz/dbplot")
install_github("edgararuiz/tidypredict")
install_github("EmilHvitfeldt/ggpage")
install_github("gabrielrvsc/HDeconometrics")
install_github("hadley/pkgdown")
install_github("hadley/precis")
install_github("hadley/strict")
install_github("hafen/trelliscopejs")
install_github("hrbrmstr/msgxtractr")
install_github("hrbrmstr/waffle")
install_github("jeremystan/aargh")
install_github("jkaupp/nord")
install_github("kevinushey/Kmisc")
install_github("MilesMcBain/deplearning")
install_github("MilesMcBain/packup")
install_github("mvuorre/brmstools")
install_github("pbiecek/breakDown")
install_github("richarddmorey/tweetRcode", subdir = "tweetRcode")
install_github("ropensci/ssh")
install_github("ropensci/tabulizer")
install_github("ropensci/tabulizerjars")
install_github("ropenscilabs/data-packages")
install_github("ropenscilabs/icon")
install_github("ropenscilabs/packagemetrics")
install_github("rstats-db/RPostgres")
install_github("rstudio/blogdown")
install_github("seasmith/AlignAssign")
install_github("sicarul/xray")
install_github("smach/rmiscutils")
install_github("stephlocke/pRojects")
install_github("swarm-lab/editR") # requires devtools::shinyAce shiny shinyFiles shinyBS rmarkdown knitr
install_github("ThinkR-open/remedy")
install_github("ThinkRstat/littleboxes")
install_github("thomasp85/patchwork")
install_github("tjmahr/WrapRmd")
install_github("trestletech/shinyAce")
install_github("vqv/ggbiplot")
install_github("wilkox/ggfittext")
install_github("WinVector/rquery")
#install_github("lantanacamara/lightgbmExplainer")
# install_github("gsimchoni/kandinsky")
# install_github("MangoTheCat/goodpractice")
# install_github("MilesMcBain/gistfo")
# install_github("r-lib/boxes")
# install_github("rich-iannone/blastula")
# install_github("ropenscilabs/available")
# install_github("Stan125/GREA")
# install_github("AntoineGuillot2/D3partitionR")
