toinstall <- c("alphahull", "Amelia", "anim.plots", "animation", "basictabler", "bigrquery", "bookdown", "brms", "C50", "car", "caret", "cartography", "changepoint", "charlatan", "choroplethr", "choroplethrMaps", "chunked", "cleanNLP", "colourpicker", "condformat", "confinterpret", "corrr", "cowplot", "cr17", "CRANsearcher", "cshapes", "ctv", "d3heatmap", "d3Tree", "data.table", "DataCombine", "dataCompareR", "DataExplorer", "dataMaid", "datapasta", "dataPreparation", "descriptr", "desctable", "DescTools", "DiagrammeR", "diceR", "diffobj", "directlabels", "drake", "dygraphs", "egg", "extrafont", "factoextra", "FFTrees", "filesstrings", "forecTheta", "fs", "funModeling", "futile.logger", "gbm", "gdalUtils", "geofacet", "geonames", "geoR", "geosphere", "GeoXp", "GGally", "ggalt", "ggbeeswarm", "ggcorrplot", "ggedit", "ggforce", "gghighlight", "ggimage", "ggiraph", "ggmap", "ggplotAssist", "ggplotgui", "ggpubr", "ggraph", "ggrepel", "ggridges", "ggsci", "ggseas", "ggsn", "ggstance", "ggtern", "ggThemeAssist", "ggthemes", "ggvis", "glmnet", "gmodels", "googleLanguageR", "gpclib", "gridExtra", "gtable", "gtrendsR", "heatmaply", "here", "hexbin", "hexSticker", "highcharter", "Hmisc", "hrbrthemes", "htmlwidgets", "igraph", "janitor", "Kmisc", "knitr", "koRpus", "lambda.tools", "leaflet", "leaflet.minicharts", "leaps", "lemon", "lessR", "liftr", "likert", "lime", "linemap", "liquidSVM", "logging", "magick", "manipulate", "mapdata", "mapedit", "mapmisc", "maps", "mapsapi", "maptools", "mapview", "metricsgraphics", "mi", "missForest", "mschart", "naniar", "naturalsort", "networkD3", "numform", "outliers", "party", "pathological", "pipefittr", "pkggraph", "placement", "plotKML", "plotly", "plotrr", "pmap", "pool", "postGIStools", "printr", "profvis", "psych", "qdapRegex", "quantmod", "questionr", "R.utils", "randomForest", "randomForestExplainer", "raster", "rasterVis", "reprex", "revealjs", "rgdal", "rgeos", "rgl", "RgoogleMaps", "rio", "riverplot", "rlang", "rmarkdown", "rms", "robets", "rpart.plot", "rpostgis", "rsample", "RTextTools", "rts", "rtweet", "rvg", "rworldmap", "scanstatistics", "scatterplot3d", "sessioninfo", "shapefiles", "shiny", "sigr", "Simpsons", "sinew", "sjmisc", "skimr", "smpic", "snakecase", "sp", "spanish", "sparklyr", "spatstat", "stm", "stow", "styler", "sugrrants", "summarytools", "swatches", "sweep", "tabplot", "tadaatoolbox", "tatoo", "textclean", "threejs", "tibbletime", "tictoc", "tidygraph", "tidyquant", "timetk", "tmap", "tmaptools", "topicmodels", "udpipe", "VIM", "visdat", "visNetwork", "waterfalls", "withr", "xgboost", "yardstick", "yarrr")

instalaos <- installed.packages() %>% data.frame()
toinstall <- setdiff(toinstall, instalaos$Package)

if (!require(pacman)) {
  install.packages("pacman")
}
pacman::p_install(toinstall,character.only = T)

gitters <- c("AliciaSchep/gglabeller", "AntoineGuillot2/D3partitionR", "AppliedDataSciencePartners/xgboostExplainer", "bhaskarvk/leaflet.extras", "ColinFay/aside", "ColinFay/tidystringdist", "datacamp/RDocumentation", "dgrtwo/gganimate", "drsimonj/twidlr", "dyerlab/popgraph", "edgararuiz/dbplot", "edgararuiz/tidypredict", "EmilHvitfeldt/ggpage", "gabrielrvsc/HDeconometrics", "gsimchoni/kandinsky", "hadley/pkgdown", "hadley/precis", "hadley/strict", "hafen/trelliscopejs", "hrbrmstr/msgxtractr", "hrbrmstr/waffle", "jeremystan/aargh", "krlmlr/styler", "lantanacamara/lightgbmExplainer", "MangoTheCat/goodpractice", "MilesMcBain/deplearning", "MilesMcBain/gistfo", "MilesMcBain/packup", "mvuorre/brmstools", "pbiecek/breakDown", "richarddmorey/tweetRcode", "rich-iannone/blastula", "r-lib/boxes", "ropensci/tabulizer", "ropensci/tabulizerjars", "ropenscilabs/available", "ropenscilabs/data-packages", "ropenscilabs/icon", "ropenscilabs/packagemetrics", "rstats-db/RPostgres", "seasmith/AlignAssign", "sicarul/xray", "smach/rmiscutils", "Stan125/GREA", "swarm-lab/editR", "ThinkR-open/remedy", "ThinkRstat/littleboxes", "thomasp85/patchwork", "trestletech/shinyAce", "vqv/ggbiplot", "wilkox/ggfittext", "WinVector/rquery")



pacman::p_install_gh(gitters, dependencies = TRUE)
